name: sup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Cache Node Template
        uses: actions/cache@v1
        env:
          cache-name: substrate-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*/Cargo.lock') }}
      - name: Build
        run: cargo build -vv --release
      - name: Run tests
        run: cargo test -vv --release
      - name: Build template
        run: |
          if [[ $(uname -s) == 'Darwin' ]];then
              export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
              export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
          else
              # DO NO THING
          fi
          ./target/release/sup new target/supnode
          cd target/supnode
          cargo build -vv --release
      - name: Upgrade template
        run: |
          ./target/release/sup update
          ./target/release/sup switch
          cargo build -vv --release
          
